---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: bhojpur-issuer
spec:
  acme:
    email: $LETSENCRYPT_EMAIL
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: issuer-account-key
    solvers:
      - dns01:
          cloudDNS:
            project: $PROJECT_NAME
            serviceAccountSecretRef:
              name: $CLOUD_DNS_SECRET
              key: key.json
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: $CERT_NAME
spec:
  secretName: $CERT_NAME
  issuerRef:
    name: bhojpur-issuer
    kind: Issuer
  dnsNames:
    - $DOMAIN
    - "*.$DOMAIN"
    - "*.ws.$DOMAIN"
